### ISSUE TITLE
is there an R6 object to represent a policy? 

### ISSUE THREAD

**Issue by berndbischl** [markdumke/reinforcelearn#15]
and can i run that?
maybe i want to compare even a handcoded policy with a learned one

**Comment by markusdumke** [comment]
yes, though it is not exported. To run a policy create an agent object and call `interact`. This also allows you to run a policy without learning.

```
library(reinforcelearn)
env = makeEnvironment("windy.gridworld")
agent = makeAgent("softmax", "table")
interact(env, agent, n.steps = 100L, learn = FALSE)
```
