### ISSUE TITLE
env printer seems to be not informative enough

### ISSUE THREAD

**Issue by berndbischl** [markdumke/reinforcelearn#20]
i guess i want to see more stuff like: 
what type is the state space?
how many actions? 
etc.

**Comment by markusdumke** [comment]
`env = makeEnvironment("windy.gridworld")
`
> <WindyGridworld>
>   Inherits from: <Gridworld>
>   Public:
>     action.names: 0 1 2 3
>     action.space: Discrete
>     actions: 0 1 2 3
>     clone: function (deep = FALSE) 
>     discount: 1
>     done: FALSE
>     episode: 0
>     episode.return: 0
>     episode.step: 0
>     initial.state: 30
>     initialize: function (...) 
>     n.actions: 4
>     n.states: 70
>     n.step: 0
>     previous.state: NULL
>     reset: function () 
>     resetEverything: function () 
>     reward: NULL
>     rewards: -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...
>     state: 30
>     state.space: Discrete
>     states: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21  ...
>     step: function (action) 
>     terminal.states: 37
>     transitions: 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  ...
>     visualize: function () 
>   Private:
>     reset_: function (env) 
>     step_: function (env, action) 
>     visualize_: function (env)
